# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.11.1
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      # - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    env_file: .env
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: 'Europe/Helsinki'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: ${ADMIN_PASSWORD}
      # Add default upstream servers
      FTLCONF_dns_upstreams: '8.8.8.8;8.8.4.4'
      # Set custom DNS records to enable access with Traefik
#      FTLCONF_dns_hosts: |-
#        192.168.1.99 beast.local
#      #Custom CNAME
#      FTLCONF_dns_cnameRecords: |-
#        pihole.${SUBDOMAIN}.${DOMAIN},beast.local
#        traefik-dashboard.${SUBDOMAIN}.${DOMAIN},beast.local
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: 'ALL'
      # Add the host machine's IP for access
      FTLCONF_LOCAL_IPV4: '192.168.1.99'
    labels:
    # Setup web GUI behind Traefik (from https://discourse.pi-hole.net/t/pihole-v6-webgui-behind-traefik/77276/12)
      - traefik.enable=true
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.services.pihole.loadbalancer.passHostHeader=true
      # Main router for all paths except "/"
      - traefik.http.routers.pihole.rule=Host(`pihole.${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.pihole.entrypoints=https   #=websecure
      - traefik.http.routers.pihole.tls=true
      # - traefik.http.routers.pihole.tls.certresolver=myresolver
      - traefik.http.routers.pihole.service=pihole
      # Root router to rewrite "/" to "/admin/"
      - traefik.http.routers.pihole-root.rule=Host(`pihole.${SUBDOMAIN}.${DOMAIN}`) && Path(`/`)
      - traefik.http.routers.pihole-root.entrypoints=https  #=websecure
      - traefik.http.routers.pihole-root.tls=true
      # - traefik.http.routers.pihole-root.tls.certresolver=myresolver
      - traefik.http.routers.pihole-root.service=pihole
      - traefik.http.routers.pihole-root.middlewares=pihole-root-rewrite
      # Middleware rewriting root to /admin/
      - traefik.http.middlewares.pihole-root-rewrite.replacePath.path=/admin/
    networks:
      - proxy
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      # - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      # - SYS_NICE
    restart: unless-stopped

networks:
  proxy:
    external: true
